# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='object_type',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importlog',
            name='year',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
