# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_auto_20181013_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
