# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-19 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_auto_20181013_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='day',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='importlog',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='importlog',
            name='result',
            field=models.CharField(default=b'In Progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
