# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-19 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0004_auto_20200519_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
