# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-19 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0005_auto_20200519_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='slug',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
