# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-23 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_importlog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importlog',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
