# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0007_auto_20200523_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='module_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
