# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0008_importlog_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
