# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0133_reportingyear_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reportingyear',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='indicator',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Database'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='activity',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'database', chained_model_field=b'database', null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Activity', verbose_name=b'Database'),
        ),
    ]
