# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-15 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='reporting_period',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Twice per week', 'Twice per week'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly')], default='', max_length=250),
            preserve_default=False,
        ),
    ]
