# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-25 20:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_itemcategory_reporting_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicreporting',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Item'),
        ),
    ]
