# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200425_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicreporting',
            name='price_amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='economicreporting',
            name='price_currency',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
