# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200427_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicreporting',
            name='reporting_item_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
