# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 21:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_economicreporting_reporting_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicreporting',
            name='item_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'LBP', max_digits=14),
        ),
    ]
