# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20200513_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('number', models.FloatField(blank=True, null=True)),
                ('source_text', models.CharField(blank=True, max_length=1500, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.ItemCategory')),
                ('item', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Item')),
            ],
        ),
    ]
