# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_monitoringreporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LASER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('laser_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='LASER_ID')),
                ('organization', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Organization Name')),
                ('focal_point_contact', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Focal Point Contact')),
                ('title', models.CharField(blank=True, default='No Title', max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief description of objectives')),
                ('status', models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Published', 'Published'), ('Discontinued', 'Discontinued'), ('Finalized', 'Finalized'), ('Finalized (but not yet published--To be published as a print profile)', 'Finalized (but not yet published--To be published as a print profile)'), ('Finalized (but not yet published--To be published as an online profile)', 'Finalized (but not yet published--To be published as an online profile)'), ('Finalized; publication underway', 'Finalized; publication underway'), ('Online profile published', 'Online profile published'), ('Online profile published', 'Online profile published')], default='Planned', max_length=1500, null=True, verbose_name='Status')),
                ('population_targeted', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Population Targeted')),
                ('sectors_covered', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Sectors covered')),
                ('report_link', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Link to the report')),
                ('required_followup', models.CharField(blank=True, max_length=1500, null=True, verbose_name='If marked as planned or ongoing, when would you like us to follow up with you?')),
                ('published_date', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Published date/Date of last update')),
                ('publication_date', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Date of publication (actual/expected)')),
                ('estimated_cost', models.CharField(blank=True, default=0.0, help_text='$', max_length=1500, null=True, verbose_name='Estimated cost')),
                ('category', models.CharField(blank=True, choices=[('Evaluation', 'Evaluation'), ('Assessment', 'Assessment'), ('Survey', 'Survey'), ('Study', 'Study')], max_length=500, null=True, verbose_name='Category')),
                ('evaluation_type', models.CharField(blank=True, choices=[('Thematic', 'Thematic'), ('UNDAF', 'UNDAF'), ('Country Programme', 'Country Programme'), ('Outcome', 'Outcome'), ('Project', 'Project')], max_length=500, null=True, verbose_name='If evaluation, what type?')),
                ('geographical_focus', models.CharField(blank=True, max_length=500, null=True, verbose_name='Geographical Focus')),
                ('UNSF_outcome', models.CharField(blank=True, max_length=500, null=True, verbose_name='UNSF Outcome')),
                ('section', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section')),
            ],
            options={
                'ordering': ('laser_id',),
                'get_latest_by': 'created',
                'verbose_name': 'LASER',
                'verbose_name_plural': 'LASER',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Draft', max_length=1500, null=True, verbose_name='Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('research_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='RESEARCH_ID')),
                ('title', models.CharField(help_text='The full title of the research', max_length=500, verbose_name='Title')),
                ('publication_year', models.CharField(help_text='The year the research was published or made available for public use', max_length=1500, verbose_name='Year of publication')),
                ('organizations', models.CharField(help_text='The organization managing the research', max_length=1500, verbose_name='Organization(s)')),
                ('researchers', models.CharField(help_text='The company or consultant(s) conducting the research', max_length=1500, verbose_name='Researcher(s)')),
                ('type', models.CharField(choices=[('Qualitative', 'Qualitative'), ('Quantitative', 'Quantitative'), ('Mixed', 'Mixed'), ('Desk Review', 'Desk Review')], max_length=500, verbose_name='Type of research')),
                ('main_sector', models.CharField(choices=[('Child Protection', 'Child Protection'), ('Health and Nutrition', 'Health and Nutrition'), ('Education', 'Education'), ('WASH', 'WASH'), ('Social Policy', 'Social Policy'), ('Cross-sectoral (Gender, Disability, Youth, etc.)', 'Cross-sectoral (Gender, Disability, Youth, etc.)')], max_length=500, verbose_name='Main Sector')),
                ('geographical_coverage', models.CharField(choices=[('Governorate', 'Governorate'), ('District', 'District'), ('Neighborhood/Village', 'Neighborhood/Village'), ('National', 'National')], max_length=500, verbose_name='Geographical Coverage')),
                ('description', models.TextField(blank=True, help_text='A brief narative on the research objectives, methodology, and findings. 250 characters maximum', max_length=250, null=True, verbose_name='Description/Abstract')),
                ('report_link', models.URLField(blank=True, help_text='URL link to access the report', max_length=2500, null=True, verbose_name='Link to Report')),
                ('recommendations', models.TextField(blank=True, help_text='Copy and paste or summarize the recommendations that the research study found', null=True, verbose_name='Recommendations')),
                ('planned_actions', models.TextField(blank=True, help_text='Note down the planned actions by either UNICEF or any other entity', null=True, verbose_name='Planned Action')),
                ('taken_actions', models.TextField(blank=True, help_text='Note down the taken actions by either UNICEF or any other entity', null=True, verbose_name='Taken Action')),
            ],
            options={
                'ordering': ('research_id',),
                'get_latest_by': 'created',
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
            },
        ),
    ]
